// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// test
Rcpp::NumericMatrix test();
RcppExport SEXP _RCGAL_test() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(test());
    return rcpp_result_gen;
END_RCPP
}
// cxhull2d
Rcpp::NumericMatrix cxhull2d(Rcpp::NumericMatrix pts);
RcppExport SEXP _RCGAL_cxhull2d(SEXP ptsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type pts(ptsSEXP);
    rcpp_result_gen = Rcpp::wrap(cxhull2d(pts));
    return rcpp_result_gen;
END_RCPP
}
// cxhull3d
Rcpp::NumericMatrix cxhull3d(Rcpp::NumericMatrix pts);
RcppExport SEXP _RCGAL_cxhull3d(SEXP ptsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type pts(ptsSEXP);
    rcpp_result_gen = Rcpp::wrap(cxhull3d(pts));
    return rcpp_result_gen;
END_RCPP
}
// cxhull3d2
Rcpp::List cxhull3d2(Rcpp::NumericMatrix pts);
RcppExport SEXP _RCGAL_cxhull3d2(SEXP ptsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type pts(ptsSEXP);
    rcpp_result_gen = Rcpp::wrap(cxhull3d2(pts));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RCGAL_test", (DL_FUNC) &_RCGAL_test, 0},
    {"_RCGAL_cxhull2d", (DL_FUNC) &_RCGAL_cxhull2d, 1},
    {"_RCGAL_cxhull3d", (DL_FUNC) &_RCGAL_cxhull3d, 1},
    {"_RCGAL_cxhull3d2", (DL_FUNC) &_RCGAL_cxhull3d2, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_RCGAL(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
