# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cxhull2d_cpp <- function(pts) {
    .Call(`_RCGAL_cxhull2d_cpp`, pts)
}

cxhull3d_cpp <- function(pts, epsilon) {
    .Call(`_RCGAL_cxhull3d_cpp`, pts, epsilon)
}

del2d_cpp <- function(pts) {
    .Call(`_RCGAL_del2d_cpp`, pts)
}

del3d_cpp <- function(pts) {
    .Call(`_RCGAL_del3d_cpp`, pts)
}

del2d_xy_cpp <- function(pts) {
    .Call(`_RCGAL_del2d_xy_cpp`, pts)
}

del2d_constrained_cpp <- function(pts, edges) {
    .Call(`_RCGAL_del2d_constrained_cpp`, pts, edges)
}

jet_normals_cpp <- function(pts, nb_neighbors) {
    .Call(`_RCGAL_jet_normals_cpp`, pts, nb_neighbors)
}

pca_normals_cpp <- function(pts, nb_neighbors) {
    .Call(`_RCGAL_pca_normals_cpp`, pts, nb_neighbors)
}

AFSreconstruction_cpp <- function(pts) {
    .Call(`_RCGAL_AFSreconstruction_cpp`, pts)
}

AFSreconstruction_perimeter_cpp <- function(pts, per) {
    .Call(`_RCGAL_AFSreconstruction_perimeter_cpp`, pts, per)
}

Poisson_reconstruction_cpp <- function(pts, normals, spacing, sm_angle, sm_radius, sm_distance) {
    .Call(`_RCGAL_Poisson_reconstruction_cpp`, pts, normals, spacing, sm_angle, sm_radius, sm_distance)
}

SurfMesh <- function(points, faces, isTriangle, triangulate, merge, normals, epsilon) {
    .Call(`_RCGAL_SurfMesh`, points, faces, isTriangle, triangulate, merge, normals, epsilon)
}

Intersection2_K <- function(rmeshes, merge, normals) {
    .Call(`_RCGAL_Intersection2_K`, rmeshes, merge, normals)
}

Intersection2_EK <- function(rmeshes, merge, normals) {
    .Call(`_RCGAL_Intersection2_EK`, rmeshes, merge, normals)
}

Difference_K <- function(rmesh1, rmesh2, merge, normals) {
    .Call(`_RCGAL_Difference_K`, rmesh1, rmesh2, merge, normals)
}

Difference_EK <- function(rmesh1, rmesh2, merge, normals) {
    .Call(`_RCGAL_Difference_EK`, rmesh1, rmesh2, merge, normals)
}

